"""Booking table

Revision ID: 015c867bf6e3
Revises: 7eb4bc19b6ac
Create Date: 2021-02-24 21:40:20.568823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '015c867bf6e3'
down_revision = '7eb4bc19b6ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_date', sa.Date(), nullable=False),
    sa.Column('book_start_time', sa.DateTime(), nullable=False),
    sa.Column('book_end_time', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['aircrafts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    # ### end Alembic commands ###
